version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    stdin_open: true